### ISSUE TITLE
Add more metric notions

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSets.jl#3]
See again [this comment](https://github.com/JuliaReach/MathematicalSystems.jl/issues/41).

Proposal. Add these:

- `volume(set)`: returns the volume of the set
- `surface(set)`: returns the surface
 
Again there is some terrain for variations since e.g. the volume of a set such that `dimension` is strictly smaller than its `space_dimension` could be either zero (Lebesgue measure of its ambient space), or not (the Lebesgue measure of the affine hull or relative volume).

**Comment by blegat** [comment]
We might rename `surface` as `surface_area` because the surface of a disc might be the circle (which is an `AbstractSet`)
